spring:
  application:
    name: SCPAPI

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  restoration-tokens:
    minutes: 15
  media:
    allowedTypes:
      - image/png
      - image/jpg
      - image/jpeg
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
        region:
          static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET:scp-api-media-storage}